from mailbox import Babyl

import requests

# this is acces token generated by me and redirected to www.acadview.com
ACCESS_TOKEN = '4988613657.ab55b96.6e5f301ba5b74680ba4b702958eb535d'

#this is common url for all the functions which we are going to perform
BASE_URL = 'https://api.instagram.com/v1/'

#get request through requests.get function

#dataofget = requests.get('https://api.github.com/events')



#owner info function who generated acess token
def owner_info():
    main_url = BASE_URL + 'users/self/?access_token=' + ACCESS_TOKEN
    my_info = requests.get(main_url).json()
    print(main_url)
    print(my_info)
    print(my_info['data']['full_name'])
    print(my_info['meta']['code'])
    print(my_info['data']['counts']['follows'])

#owner_info()


#info of a particular user
def get_user_info_by_user_name(insta_user_name):
    main_url = BASE_URL + 'users/search?q=' + insta_user_name + '&access_token=' + ACCESS_TOKEN
    user_info = requests.get(main_url).json()
    #print(user_info)
    return user_info['data'][0]['id']



#get_user_info_by_user_name("bot_demo")

#to see post of particular user
#https://api.instagram.com/v1/users/{user-id}/media/recent/?access_token=ACCESS-TOKEN
def see_post_of_user(user_name):
    insta_user_id = get_user_info_by_user_name(user_name)
    #print("url is"+insta_user_id)
    url = BASE_URL + 'users/' + insta_user_id + '/media/recent/?access_token=' + ACCESS_TOKEN
    #print(url)
    recent_post = requests.get(url).json()
    #print(recent_post['data'][0]['id'])
    print(recent_post['data'][0]['link'])
    return recent_post['data'][0]['id']

#see_post_of_user("bot_demo")


#fxn to like the post

def like_post_of_user(user_name):
      post_id =see_post_of_user(user_name)
      #print(post_id)
      payload = {"access_token":ACCESS_TOKEN}
      req_url = BASE_URL + "media/" + post_id +"/likes"
      like_response = requests.post(req_url,payload).json()
      #print(like_response)

#like_post_of_user("bot_demo")


#fxn to see comment on user post
#https://api.instagram.com/v1/media/{media-id}/comments?access_token=ACCESS-TOKEN
def see_comment_on_post(user_name):
    post_id = see_post_of_user(user_name)
    request_url = BASE_URL + 'media/' + post_id + '/comments?access_token='+ACCESS_TOKEN
    #print (request_url)
    comments = requests.get(request_url).json()
    #print(comments)



#see_comment_on_post("bot_demo")

#fxn to do comment on post
def do_comment_on_post(user_name):
    post_id = see_post_of_user(user_name)

    request_url = BASE_URL + 'media/' + post_id + '/comments?access_token=' + ACCESS_TOKEN

    #print (request_url)
    payload = {"access_token": ACCESS_TOKEN,'text':'gud'}
    comment_response = requests.post(request_url, payload).json()
    print(comment_response)
    return(comment_response['data']['id'])


#do_comment_on_post("bot_demo")


#https://api.instagram.com/v1/media/{media-id}/comments/{comment-id}?access_token=A
#delete a comment on a post
def delete_post(user_name):
    post_id = see_post_of_user(user_name)
    print(post_id)
    comment_id = do_comment_on_post(user_name)
    print(comment_id)

    request_url = BASE_URL + 'media/' + post_id + '/comments/'+comment_id + '?access_token='+ACCESS_TOKEN
    print(request_url)
    delete_comment = requests.delete(request_url).json()
    print(delete_comment)
delete_post("bot_demo")