#request lib to do post,get,delete request for insta
import requests

# this is acces token generated by me and redirected to www.acadview.com
ACCESS_TOKEN = '4988613657.ab55b96.6e5f301ba5b74680ba4b702958eb535d'
print("...**/\............My Access token of the app is........./\**......"+ACCESS_TOKEN)
#this is common url for all the functions which we are going to perform
BASE_URL = 'https://api.instagram.com/v1/'


#owner info function who generated acess token
def self_info():
    main_url = BASE_URL + 'users/self/?access_token=' + ACCESS_TOKEN
    my_info = requests.get(main_url).json()
    #print(main_url)
    print("....info about user who generted access token.....")
    print(my_info)
    print("Full name of self..."+my_info['data']['full_name'])
    print("code of self...."+str(my_info['meta']['code']))
#self_info()


#info of a particular user by serach method
def get_user_info_by_user_name(insta_user_name):
    main_url = BASE_URL + 'users/search?q=' + insta_user_name + '&access_token=' + ACCESS_TOKEN
    user_info = requests.get(main_url).json()
    print(".....hence info of searched user is.......")
    print(user_info)
    return user_info['data'][0]['id']
#get_user_info_by_user_name("bot_demo")




#to see post of particular user by name
def see_post_of_user(user_name):
    insta_user_id = get_user_info_by_user_name(user_name)
    print("Id of searched instagram user....."+insta_user_id)
    url = BASE_URL + 'users/' + insta_user_id + '/media/recent/?access_token=' + ACCESS_TOKEN
    recent_post = requests.get(url).json()
    print("The complete information of the instagram user media...." )
    print(recent_post)
    print("it is the id of recent post of secarhed user......."+recent_post['data'][0]['id'])
    print("it is the link of a particular post done by user who have serached out ...."+recent_post['data'][0]['link'])
    return recent_post['data'][0]['id']
#see_post_of_user("bot_demo")




#fxn to like the post of a particular user who accepted your sandbox request
def like_post_of_user(user_name):
      post_id =see_post_of_user(user_name)
      print("post Id oF User is ........."+post_id)
      payload = {"access_token":ACCESS_TOKEN}
      req_url = BASE_URL + "media/" + post_id +"/likes"
      like_response = requests.post(req_url,payload).json()
      print("...........Response of the like post on instagram user....")
      print(like_response)
#like_post_of_user("bot_demo")




#fxn to see comment on user post
def see_comment_on_post(user_name):
    post_id = see_post_of_user(user_name)
    request_url = BASE_URL + 'media/' + post_id + '/comments?access_token='+ACCESS_TOKEN
    #print (request_url)
    comments = requests.get(request_url).json()
    print("Response of get request on comments which display comments on particular media.....")
    print(comments)
#see_comment_on_post("bot_demo")




#fxn to do comment on post
def do_comment_on_post(user_name):
    post_id = see_post_of_user(user_name)

    request_url = BASE_URL + 'media/' + post_id + '/comments?access_token=' + ACCESS_TOKEN

    #print (request_url)
    payload = {"access_token": ACCESS_TOKEN,'text':'gud'}
    comment_response = requests.post(request_url, payload).json()
    print("..........Response of post request on comments and do the comment on user post.....")
    print(comment_response)
    return(comment_response['data']['id'])#comment_id


#do_comment_on_post("bot_demo")


#https://api.instagram.com/v1/media/{media-id}/comments/{comment-id}?access_token=A
#delete a comment on a post
def delete_post(user_name):
    post_id = see_post_of_user(user_name)
    print("user's post id is...."+post_id)
    comment_id = do_comment_on_post(user_name)
    print("comment id is...."+comment_id)

    request_url = BASE_URL + 'media/' + post_id + '/comments/'+comment_id + '?access_token='+ACCESS_TOKEN
    print(request_url)
    delete_comment = requests.delete(request_url).json()
    print("........Response of delete request comment...")
    print(delete_comment)
#delete_post("bot_demo")





print(".....********.......This Is My instabot App....*****.....")
print("........You can choose one option at a time by pressing 1 to 7 digit....")
print("....>>### Enter 1 for self information  ###<<......")
print("....>>### Enter 2 for User information  ###<<......")
print("....>>### Enter 3 for see user post  ###<<......")
print("....>>### Enter 4 to do like on user post ###<<......")
print("....>>### Enter 5 to see the recent comments on post ###<<......")
print("....>>### Enter 6 to do comment on the instagram user post  ###<<......")
print("....>>### Enter 7 to delete the particular comment by comment_id  ###<<......")


choice = input("*******.......PLEASE ENTER A RELEVANT CHOICE FROM(1 TO 8)....*******...   ")
if choice=='1':
    self_info()
elif choice=='2':
    get_user_info_by_user_name("bot_demo")
elif choice=='3':
    see_post_of_user("bot_demo")
elif choice=='4':
    like_post_of_user("bot_demo")
elif choice=='5':
    see_comment_on_post("bot_demo")
elif choice=='6':
    do_comment_on_post("bot_demo")
elif choice=='7':
    delete_post("bot_demo")
else:
    print("........wrong choice entered.....thank you.....")


