#request lib to do post,get,delete request for insta
import requests

# this is acces token generated by me and redirected to www.acadview.com
ACCESS_TOKEN = '4988613657.ab55b96.6e5f301ba5b74680ba4b702958eb535d'
print("...**/\............My Access token of the app is........./\**......"+ACCESS_TOKEN)
#this is common url for all the functions which we are going to perform
BASE_URL = 'https://api.instagram.com/v1/'



#_________________________________________________________________________________________________________
#owner info function who generated acess token
def self_info():
    main_url = BASE_URL + 'users/self/?access_token=' + ACCESS_TOKEN
    my_info = requests.get(main_url).json()
    #print(main_url)
    print("....info about user who generted access token.....")
    print(my_info)
#self_info()


#--------------------------------------------------------------------------------------------------------
#complete infomation of owner
def complete_info_of_self():
    main_url = BASE_URL + 'users/self/?access_token=' + ACCESS_TOKEN
    my_info = requests.get(main_url).json()
    print(".............** Here Is the complete detail of owner **.....")
    print("Name of owner.... "+my_info['data']['full_name'])
    print("username of owner.... " + my_info['data']['username'])
    print("id of owner.... " + my_info['data']['id'])
    print("profile picture of owner.... " + my_info['data']['profile_picture'])
    print("Total media of owner.... " + str(my_info['data']['counts']['media']))
    print("Follwers of owner.... " + str(my_info['data']['counts']['followed_by']))
    print("following of owner.... " + str(my_info['data']['counts']['follows']))
    if my_info['data']['website']!='':
        print("........website of the owner....   " + my_info['data']['website'])
    else:
        print("........website of the owner....   " + "No site of owner")
    if my_info['data']['bio']!='':
        print("........bio of the owner....   " + my_info['data']['bio'])
    else:
        print("........bio of the owner....   " + "No bio of owner")
#complete_info_of_self()

#***************************************************************************************************************************
#info of a particular user by serach method
def get_user_info_by_user_name(insta_user_name):
    main_url = BASE_URL + 'users/search?q=' + insta_user_name + '&access_token=' + ACCESS_TOKEN
    user_info = requests.get(main_url).json()
    print(".....hence information of searched user is.......")
    print(user_info)
    return user_info['data'][0]['id'] #id of instagram user
#get_user_info_by_user_name("bot_demo")


###########################################################################################################################
#get user_id
def get_user_id(user_name):
    main_url = BASE_URL + 'users/search?q=' + insta_user_name + '&access_token=' + ACCESS_TOKEN
    user_info = requests.get(main_url).json()
    if user_info['data'][0]['id'] == '':
        print("...... USER ID IS NOT FOUND....")
    else:
        print("Id of user is..........   " + user_info['data'][0]['id'])
        return user_info['data'][0]['id']  # id of instagram user



#&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&7
# fxn to display complete info of user
def get_user_complete_info(insta_user_name):
    insta_user_id = get_user_id(insta_user_name)
    print("Id of searched instagram user....." + insta_user_id)
    main_url = BASE_URL + 'users/search?q=' + insta_user_name + '&access_token=' + ACCESS_TOKEN
    user_info = requests.get(main_url).json()
    #print(user_info)
    print("........Name of the user....   "+user_info['data'][0]['username'])
    print("........Profile picture of the user....   " + user_info['data'][0]['profile_picture'])
    print("........full_name of the user....   " + user_info['data'][0]['full_name'])
    if user_info['data'][0]['website']!='':
        print("........website of the user....   " + user_info['data'][0]['website'])
    else:
        print("........website of the user....   " + "No site of this particular user")
    if user_info['data'][0]['bio']!='':
        print("........bio of the user....   " + user_info['data'][0]['bio'])
    else:
        print("........bio of the user....   " + "No bio of this particular user")



#______________________________________________________________________________________________________________________________
#to see post of particular user by name
def see_post_of_user(user_name):
    insta_user_id = get_user_id(user_name)
    url = BASE_URL + 'users/' + insta_user_id + '/media/recent/?access_token=' + ACCESS_TOKEN
    recent_post = requests.get(url).json()
    print("The complete information of the instagram user media...." )
    print(recent_post)
    print("it is the id of recent post of secarhed user......."+recent_post['data'][0]['id'])
    print("it is the link of a particular post done by user who have serached out and you are going to like and comment...."+recent_post['data'][0]['link'])
    return recent_post['data'][0]['id']  #recent user post_id
#see_post_of_user("bot_demo")


#_________________________________________________________________________________________________________________________________
#this fxn will return post id of user
def get_post_id(user_name):
    insta_user_id = get_user_id(user_name)
    url = BASE_URL + 'users/' + insta_user_id + '/media/recent/?access_token=' + ACCESS_TOKEN
    recent_post = requests.get(url).json()
    print("it is the link of a particular post done by user who have serached out and you are going to like and comment...." +recent_post['data'][0]['link'])
    #print(recent_post)
    for number in range(0, len(recent_post["data"]), 1):  # traversingh all post id of user
        pass


    print("-------------Total Number Of posts-------- " + str(number))
    return recent_post['data'][0]['id']  # recent user post_id



###############################################################################################################################
#fxn to like the post of a particular user who accepted your sandbox request
def like_post_of_user(user_name):
      post_id =get_post_id(user_name)
      print("post Id oF User is ........."+post_id)
      payload = {"access_token":ACCESS_TOKEN}
      req_url = BASE_URL + "media/" + post_id +"/likes"
      like_response = requests.post(req_url,payload).json()
      print("...........Response of the post request(to do like) on instagram user post....")
      print(like_response)
      if like_response['meta']['code']==200:
          print(".....yes you have done succesfully like on the post.....")
      else:
          print("Please try again to do like")

#like_post_of_user("bot_demo")



#---------------------------------------------------------------------------------------------------------------------------
#fxn to see comment on user post
def see_comment_on_post(user_name):
    post_id = get_post_id(user_name)
    request_url = BASE_URL + 'media/' + post_id + '/comments?access_token='+ACCESS_TOKEN
    #print (request_url)
    comments = requests.get(request_url).json()
    print("Response of get request on comments which display comments on particular media.....")
    print(comments)
    return comments
#see_comment_on_post("bot_demo")



#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#fxn to do comment on post
def do_comment_on_post(user_name):
    post_id = get_post_id(user_name)
    request_url = BASE_URL + 'media/' + post_id + '/comments?access_token=' + ACCESS_TOKEN
    comment_you_want_todo = input("Please enter the comment you want to do on post_id   "+str(post_id)+"   ")
    #print (request_url)
    payload = {"access_token": ACCESS_TOKEN,'text':comment_you_want_todo}
    comment_response = requests.post(request_url, payload).json()
    print("..........Response of post request on comments and do the comment on user post.....")
    print(comment_response)
    if comment_response['meta']['code']==200:
        print(".... you have done succesfully comment on the post and yous comment is ...  "+comment_you_want_todo)
    else:
        print("_________________please try after sometime__________donot need to worry it will work fine_______")
    return(comment_response['data']['id'])#comment_id
#do_comment_on_post("bot_demo")


#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
#serach comment according to particular user to delete that comment
def return_comment_id(user_name,post_id):

    comment = input("______Please enter the comment you want to delete________   ")
    recent_comments = BASE_URL + "media/" + str(post_id) + "/comments?access_token=" + ACCESS_TOKEN
    recent_comments = requests.get(recent_comments).json()#get to see the comment
    for i in range(0, len(recent_comments["data"]), 1): #one by one each
        if comment in recent_comments['data'][i]['text']:
            print("______comment is found________")
            return recent_comments['data'][i]['id']




#----------------------------------------------------------------------------------------------------------------------
#delete a comment on a post
def delete_post_bycomment(user_name):
    post_id = get_post_id(user_name)
    print("user's post id is...."+post_id)
    comment_id = return_comment_id(user_name,post_id)
    if comment_id==None:
        print("============your comment is not found==========================")
    else:
        print("comment id is...."+str(comment_id))
        request_url = BASE_URL + 'media/' + str(post_id) + '/comments/'+str(comment_id) + '?access_token='+ACCESS_TOKEN
        #print(request_url)
        delete_comment = requests.delete(request_url).json()
        print("........Response of delete request comment...")
        print(delete_comment)
        if delete_comment['meta']['code']==200:
            print("succesfully deleted your entered comment....")
        else:
            print("not succesfully deleted your comment--------------------")
#delete_post("bot_demo")



###########################################################################################################################
#average fxn
def average_number_in_comment(post_id):
    words_count = 0
    url = BASE_URL + "media/" + str(post_id) + "/comments/?access_token=" + ACCESS_TOKEN
    comment_data = requests.get(url).json()
    comments_list = [] #empty list
    if len(comment_data['data']) != 0:
        for comment in comment_data['data']:
            comments_list.append(comment['text'])#appending each word
            length_of_word_in_list = len(comment['text'].split())#count the length by ignoring space
            words_count = words_count + length_of_word_in_list
        average = float(words_count)/len(comments_list)#calculatin avg
        print("--------------------hence average is---------%.2f   "%(average))
    else:
        print("__________________There is no comment on this selected post_____")


#_____________________________________________________________________________________________________________________
#secrh comment by word to delete that
def delete_comment_by_word(insta_user):
    comment_list = []
    post_id = get_post_id(insta_user)
    word_want_to_search = input("_________________Please enter the word you want to search_______________________________")
    request_url = BASE_URL + 'media/' + post_id + '/comments?access_token=' + ACCESS_TOKEN
    # print (request_url)
    comments = requests.get(request_url).json()
    comments_result = comments['data']


    for i in range(len(comments_result)): # accessing the ecah word in text
        single_word = comments_result[i]['text'].split()

        if word_want_to_search in single_word:
            comment_list.append(comments_result[i]['id'])
    if len(comment_list):
        for i in comment_list:
            request_url = BASE_URL + 'media/' + post_id + '/comments/' + str(i) + '?access_token=' + ACCESS_TOKEN
            # print(request_url)
            delete_comment = requests.delete(request_url).json()
        print("________________comment is deleted succesfully______________")
    else:
        print("_____________comment is not found__________")


#---------------------------------------------------------------------------------------------------------------------
#_____________________________________________________________________________________________________________________

#to enter in the while loop to repeat this task again and again
count = 'y'
while count=='y':


    print(".....********.......This Is My instabot App....*****.....")
    print("........You can choose one option at a time by pressing 1 to 11 digit....")
    print("....>>### Enter 1 for self information  ###<<......")
    print("....>>### Enter 2 for complete information of owner ###<<......")
    print("....>>### Enter 3 for User information  ###<<......")
    print("....>>### Enter 4 for User complete infomation information  ###<<......")
    print("....>>### Enter 5 for see user post  ###<<......")
    print("....>>### Enter 6 to do like on user post ###<<......")
    print("....>>### Enter 7 to see the recent comments on post ###<<......")
    print("....>>### Enter 8 to do comment on the instagram user post  ###<<......")
    print("....>>### Enter 9 to delete the particular comment by comment_id  ###<<......")
    print("....>>### Enter 10 to print the average number of words per comment  ###<<......")
    print("....>>### Enter 11 to delete the comment by word  ###<<......")

    choice = input("*******.......PLEASE ENTER A RELEVANT CHOICE FROM(1 TO 11)....*******...   ")
    if choice=='1':
        self_info()

    elif choice=='2':
        complete_info_of_self()

    elif choice=='3':
        insta_user_name = input(".... Please Enter Name oF user you want to search detail you have option to enter bot_demo and gnimullana.....    ")
        if insta_user_name=='bot_demo':
            get_user_info_by_user_name(insta_user_name)
        elif insta_user_name=='gnimullana':
            get_user_info_by_user_name(insta_user_name)
        else:
            print("...... PLEASE ENTER A VALID NAME FROM OPTION PROVIDED TO YOU.....")


    elif choice=='4':
        insta_user_name = input(".... Please Enter Name oF user you want to see complete detail you have option to enter bot_demo and gnimullana.....    ")
        if insta_user_name=='bot_demo':
            get_user_complete_info(insta_user_name)
        elif insta_user_name=='gnimullana':
            get_user_complete_info(insta_user_name)
        else:
            print("...... PLEASE ENTER A VALID NAME FROM OPTION PROVIDED TO YOU.....")


    elif choice=='5':
        insta_user_name = input(".... Please Enter Name oF user whose post you want to see you have option to enter bot_demo and gnimullana.....     ")
        if insta_user_name == 'bot_demo':
            see_post_of_user(insta_user_name)
        elif insta_user_name=='gnimullana':
            see_post_of_user(insta_user_name)
        else:
            print("...... PLEASE ENTER A VALID NAME FROM OPTION PROVIDED TO YOU.....")

    elif choice=='6':
        insta_user_name = input(".... Please Enter Name oF user whom post yoy want to like you have option to enter bot_demo and gnimullana.....   ")
        if insta_user_name == 'bot_demo':
            like_post_of_user(insta_user_name)
        elif insta_user_name=='gnimullana':
            like_post_of_user(insta_user_name)
        else:
            print("...... PLEASE ENTER A VALID NAME FROM OPTION PROVIDED TO YOU.....")

    elif choice=='7':
        insta_user_name = input(".... Please Enter Name oF user to see the comment on his post you have option to enter bot_demo and gnimullana.....     ")
        if insta_user_name == 'bot_demo':
            see_comment_on_post(insta_user_name)
        elif insta_user_name=='gnimullana':
            see_comment_on_post(insta_user_name)
        else:
            print("...... PLEASE ENTER A VALID NAME FROM OPTION PROVIDED TO YOU.....")

    elif choice=='8':
        insta_user_name = input(".... Please Enter Name oF user on which you want to comment you have option to enter bot_demo and gnimullana.....     ")
        if insta_user_name == 'bot_demo':
            do_comment_on_post(insta_user_name)
        elif insta_user_name=='gnimullana':
            do_comment_on_post(insta_user_name)
        else:
            print("...... PLEASE ENTER A VALID NAME FROM OPTION PROVIDED TO YOU.....")

    elif choice=='9':
        insta_user_name = input(".... Please Enter Name oF user whom you want to delete comment you have option to enter bot_demo and gnimullana.....     ")
        if insta_user_name == 'bot_demo':
            delete_post_bycomment(insta_user_name)
        elif insta_user_name=='gnimullana':
            delete_post_bycomment(insta_user_name)
        else:
            print("...... PLEASE ENTER A VALID NAME FROM OPTION PROVIDED TO YOU.....")

    elif choice == '10':
        insta_user_name = input(".... Please Enter Name oF user whom you want to delete comment you have option to enter bot_demo and gnimullana.....     ")
        if insta_user_name == 'bot_demo':

            post_id = get_post_id(insta_user_name)
            average_number_in_comment(post_id)
        elif insta_user_name=='gnimullana':
            post_id = get_post_id(insta_user_name)
            average_number_in_comment(post_id)
        else:
            print("...... PLEASE ENTER A VALID NAME FROM OPTION PROVIDED TO YOU.....")

    elif choice=='11':
        insta_user_name = input(".... Please Enter Name oF user whom you want to delete comment you have option to enter bot_demo and gnimullana.....     ")
        if insta_user_name == 'bot_demo':
            delete_comment_by_word(insta_user_name)
        elif insta_user_name=='gnimullana':
            delete_comment_by_word(insta_user_name)
        else:
            print("...... PLEASE ENTER A VALID NAME FROM OPTION PROVIDED TO YOU.....")


    else:
        print("........wrong choice entered.....thank you.....")

    print("*************.........Do You want to use this app again........***********")
    count = input("... #####  Enter 'y' if you want to use this app again #### .....")
print("..... Hope you use this app in mannerful way.... Thanx.... :) ")